spring:
  application:
    name: word_checker
  datasource:
    url: jdbc:mysql://localhost:3306/wcdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 980702
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
file:
  upload-dir: ./file-storage
  max-concurrent-tasks: 20
  max-storage-mb: 1024